### ISSUE TITLE
Support for MCPatcher's "Random Mobs" and OptiFine's "Random Entities"

### ISSUE THREAD

**Issue by NatoBoram** [Digifox03/reselect#5]
* Basically https://github.com/Digifox03/variedMobs/issues/18

> I think there would be more demand for compatibility with previous formats before new formats are necessary. For example, I want to use [Alternate Entities](https://faithful.team/alternate-entities/), but it's not really possible at the moment.
> * [MCPatcher's "Random Mobs"](https://bitbucket.org/prupe/mcpatcher/wiki/Random_Mobs)
> * [OptiFine's "Random Entities"](https://github.com/sp614x/optifine/blob/master/OptiFineDoc/doc/random_entities.properties)

I imagine it's a non-goal for this lib, too?

**Comment by Digifox03** [comment]
The purpose of this library is to provide a replacement format, not to use the previous ones.
If there will be a way to provide compatibility, it will be part of Varied Mob Textures, a conversion tool, or a standalone mod.
